### ISSUE TITLE
BUG: during auto-assert mode + IEX shell sometimes changes in the expression are reverted back to prev. values

### ISSUE THREAD

**Issue by mindreframer** [zachallaun/mneme#7]
Repro here: 
- https://github.com/mindreframer/mneme_autoaccept

With a short screencast: 
https://user-images.githubusercontent.com/1232/221042131-ea8c8927-f734-491e-b29d-8d6d84744493.mov

Interestingly when the code to restart the Mneme server is changed to look like in this commit: https://github.com/mindreframer/mneme/commit/4c17f0360f2b6dea497a2878d252dfbae7347749

it works OK.

**Comment by zachallaun** [comment]
Interesting — I wonder if `restart_child` is not completing successfully. I’m ignoring the return value which is a mistake. I’ll try to look into this later tonight!

**Comment by zachallaun** [comment]
Should be fixed in v0.1.4 😄 Thanks for the report & repro! Please do let me know if anything else seems awry.

**Comment by mindreframer** [comment]
@zachallaun Great, it seems to work! Thanks for the super quick fix!
