### ISSUE TITLE
Multiline string pattern not generated as heredoc

### ISSUE THREAD

**Issue by JonasGruenwald** [zachallaun/mneme#84]
Hi, I'm trying to use mneme for the first time, I read this section [in the docs here](https://hexdocs.pm/mneme/generated_patterns.html#strings-and-binaries):

> If the string is printable and contains a newline, a heredoc pattern using """ is generated.

But when I do an auto assert with a string containing a newline like so:

```elixir
auto_assert email.html_body
```

I get 

```elixir
    auto_assert "<html>\n  <head>\n    <title> [...rest removed]" <- email.html_body
```

As a regular string, instead of multiline heredoc.

Am I doing something wrong / missing something with this?
Version is 0.8.2

**Comment by JonasGruenwald** [comment]
My bad, I skipped over the part about multiple patterns because I didn't really understand it, now I get that I had to use j/k to select the heredoc version in the review never mind!

Thanks for your work on this library, works great so far :)

**Comment by zachallaun** [comment]
Glad you got it figured out and that things are working well for you now!
