### ISSUE TITLE
Crash when cycling through patterns

### ISSUE THREAD

**Issue by JonasGruenwald** [zachallaun/mneme#85]
Hello again! I've encountered an issue with a specific string that will not allow cycling through auto assert patterns with j/k, instead mneme will crash after entering j/k.

It's hard for me to tell which part of the string is causing this, it was a larger HTML doc and I stripped it down by deleting parts until it stopped crashing, below is the last version that still crashes mneme, deleting either of the paragraphs will stop it from crashing

```elixir
defmodule WibbleTest do
  use ExUnit.Case
  use Mneme

  defp problematic_output do
    """
    <html>
      <body>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </p>

        <p>
          Lorem ipsum dolor sit amet,
          Lorem Ipsum
        </p>
      </body>
    </html>
    """
  end

  test "meneme test" do
    auto_assert problematic_output()
  end
end
```

## Steps to reproduce

1. Set up a project with the test above
2. Run `mix test`

```
~/Projects/temp/wibble → mix test

[1] New · test meneme test (WibbleTest)
test/wibble_test.exs:24

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  -  auto_assert problematic_output()
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  +  auto_assert "<html>\n  <body>\n    <p>\n      Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n    </p>\n\n    <p>\n      Lorem ipsum dolor sit amet,\n      Lorem Ipsum\n    </p>\n  </body>\n</html>\n" <-
  +                problematic_output()
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Accept new assertion?
> j
y yes  n no  s skip  ❮ J/j ●○ k/K ❯
```

2. enter j (or k) and press enter

Output:

```
  1) test meneme test (WibbleTest)
     test/wibble_test.exs:23
     ** (Mneme.InternalError) Mneme encountered an internal error. This is likely a bug in Mneme.

     Please consider reporting this error at https://github.com/zachallaun/mneme/issues. Thanks!

     ** (FunctionClauseError) no function clause matching in Mneme.Terminal.tag_line/1
         (mneme 0.8.2) lib/mneme/terminal.ex:193: Mneme.Terminal.tag_line({[], :green})
         (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
         (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
         (mneme 0.8.2) lib/mneme/terminal.ex:116: Mneme.Terminal.format_semantic_diff/2
         (mneme 0.8.2) lib/mneme/terminal.ex:32: Mneme.Terminal.message/4
         (mneme 0.8.2) lib/mneme/terminal.ex:21: Mneme.Terminal.prompt!/3
         (mneme 0.8.2) lib/mneme/patcher.ex:79: Mneme.Patcher.patch!/4
         (mneme 0.8.2) lib/mneme/patcher.ex:64: Mneme.Patcher.patch!/3
         (mneme 0.8.2) lib/mneme/server.ex:167: Mneme.Server.do_patch_assertion/2
         (mneme 0.8.2) lib/mneme/server.ex:158: Mneme.Server.handle_continue/2
         (stdlib 5.2.2) gen_server.erl:1085: :gen_server.try_handle_continue/3
         (stdlib 5.2.2) gen_server.erl:995: :gen_server.loop/7
         (stdlib 5.2.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

     
     code: auto_assert problematic_output()
     stacktrace:
       (mneme 0.8.2) lib/mneme/assertion.ex:253: Mneme.Assertion.handle_assertion/4
       (mneme 0.8.2) lib/mneme/assertion.ex:190: Mneme.Assertion.run!/3
       test/wibble_test.exs:24: (test)

.
Finished in 1.2 seconds (0.00s async, 1.2s sync)
1 doctest, 1 test, 1 failure

Randomized with seed 278008
```

## Notes

* As mentioned, deleting either of the `<p>` tags from the string stops causing the crash
* I was able to work around this issue (I wanted to select the heredoc version for the string) by using `@mneme default_pattern: :last, force_update: true, action: :accept` as described in the docs, the generated heredoc pattern looks correct to me in the file

**Comment by JonasGruenwald** [comment]
I've narrowed it down a bit, I think it has nothing to do with the characters in the markup, it's something about the newlines.
For example just this on its own is enough to crash mneme for me when trying to cycle through to the next pattern:

```elixir
defp problematic_output do
  "\n"
end
```

This works fine, a newline surrounded by other characters

```elixir
defp working_output do
  "wibble\nwobble"
end
```

But this again will cause the crash, I think this is the issue with my original example as well, a newline without a non-newline character before/after

```elixir
defp problematic_output do
  "wibble\n\nwobble"
end
```

**Comment by zachallaun** [comment]
Thank you! I'll look into this tomorrow. 

One thing that would be helpful: can you upgrade to 0.9.0-alpha.0 and see if the problem persists?

**Comment by JonasGruenwald** [comment]
> One thing that would be helpful: can you upgrade to 0.9.0-alpha.0 and see if the problem persists?

Yeah I've just tested it by cloning the latest main branch of mneme and referencing it as a path dependency, the issue still persists.
What happens is, in case of my last example, `Mneme.Terminal.tag_lines` is called for `ins` (insertions I assume) with lines like this:

```elixir
[
  ["auto_assert ", {"\"\"\"", :green}],
  {"            wibble", :green},
  {[], :green},
  {"            wobble\\", :green},
  [{"            \"\"\"", :green}, " ", {"<-", :green}, " problematic_output()"]
]
```

And for `{[], :green},` there is no `tag_line/1` function clause matching (tuple where the first element is a list), so it raises the `FunctionClauseError`.

I think something is wrong there, I think the line should have the type. `Diff.Formatter.formatted_line()` but instead of a string, the first element of the tuple is that empty list.
I would have liked to find the root cause but I think it might be somewhere in the Diff module and I'm a little lost there

**Comment by zachallaun** [comment]
Thanks for the sleuthing! Things do get a little tricky in the diff module; I'll get do the bottom of it.

**Comment by zachallaun** [comment]
@JonasGruenwald I believe this has been fixed! If you have a moment and can try to reproduce against `main` again, I'd greatly appreciate it!

**Comment by JonasGruenwald** [comment]
@zachallaun Yes it works after your changes, thanks for figuring this out so quickly 🙏

**Comment by zachallaun** [comment]
Thank for you confirming! I'll release as an alpha release when I'm able, so that you can depend on it to avoid the path dependency.

**Comment by tcoopman** [comment]
I've also ran into this. main indeed fixes it.
