### ISSUE TITLE
`mix mneme.watch`: add flag to only run stale tests

### ISSUE THREAD

**Issue by tcoopman** [zachallaun/mneme#91]
Running all tests might be a bit slow, but only running stale tests again will be quite a bit faster

**Comment by zachallaun** [comment]
Great point! Mneme currently passes *all* flags to an underlying `mix test` command; what happens if you pass `--stale` right now? (I'm not in a position to test at the moment.)

**Comment by tcoopman** [comment]
well, it just works :tada:

**Comment by zachallaun** [comment]
That's awesome then! I should definitely add that to the docs somewhere.

**Comment by zachallaun** [comment]
Opened #92 to track documentation-related stuff for `mix mneme.watch`
